name = "TachikomaDemos"
uuid = "e83297aa-c13c-4c35-9829-13c52dfbaaf0"
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Tachikoma = "468859d6-42d8-48b7-8ad9-1d312e0e3b0a"

[compat]
ColorTypes = "0.12.1"
CommonMark = "0.8.16"
FreeTypeAbstraction = "0.10.8"
Match = "2.4.1"
