[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Tachikoma = "468859d6-42d8-48b7-8ad9-1d312e0e3b0a"

[compat]
Documenter = "1"
DocumenterVitepress = "0.1"
